global using System;
global using System.Collections.Generic;
global using System.Diagnostics;
global using System.IO;
global using System.Runtime.CompilerServices;
global using System.Runtime.InteropServices;
global using System.Text.Json;
global using System.Text.Json.Serialization;
global using Fahrenheit;
